import type {EditorThemeClasses} from 'lexical';

const defaultTheme: EditorThemeClasses = {
  ltr: 'rte-ltr',
  rtl: 'rte-rtl',
  placeholder: 'rte-placeholder',
  paragraph: 'rte-paragraph',
  quote: 'rte-quote',
  heading: {
    h1: 'rte-heading-h1',
    h2: 'rte-heading-h2',
    h3: 'rte-heading-h3',
    h4: 'rte-heading-h4',
    h5: 'rte-heading-h5',
    h6: 'rte-heading-h6',
  },
  list: {
    nested: {
      listitem: 'rte-nested-listitem',
    },
    ol: 'rte-list-ol',
    ul: 'rte-list-ul',
    listitem: 'rte-listitem',
    listitemChecked: 'rte-listitem-checked',
    listitemUnchecked: 'rte-listitem-unchecked',
  },
  image: 'rte-image',
  link: 'rte-link',
  text: {
    bold: 'rte-text-bold',
    italic: 'rte-text-italic',
    underline: 'rte-text-underline',
    strikethrough: 'rte-text-strikethrough',
    underlineStrikethrough: 'rte-text-underline-strikethrough',
    code: 'rte-text-code',
    highlight: 'rte-text-highlight',
    subscript: 'rte-text-subscript',
    superscript: 'rte-text-superscript',
  },
  code: 'rte-code',
  codeHighlight: {
    atrule: 'rte-token-attr',
    attr: 'rte-token-attr',
    boolean: 'rte-token-property',
    builtin: 'rte-token-selector',
    cdata: 'rte-token-comment',
    char: 'rte-token-selector',
    class: 'rte-token-function',
    'class-name': 'rte-token-function',
    comment: 'rte-token-comment',
    constant: 'rte-token-property',
    deleted: 'rte-token-property',
    doctype: 'rte-token-comment',
    entity: 'rte-token-operator',
    function: 'rte-token-function',
    important: 'rte-token-variable',
    inserted: 'rte-token-selector',
    keyword: 'rte-token-attr',
    namespace: 'rte-token-variable',
    number: 'rte-token-property',
    operator: 'rte-token-operator',
    prolog: 'rte-token-comment',
    property: 'rte-token-property',
    punctuation: 'rte-token-punctuation',
    regex: 'rte-token-variable',
    selector: 'rte-token-selector',
    string: 'rte-token-selector',
    symbol: 'rte-token-property',
    tag: 'rte-token-property',
    url: 'rte-token-operator',
    variable: 'rte-token-variable',
  },
  table: 'rte-table',
  tableCell: 'rte-table-cell',
  tableCellHeader: 'rte-table-cell-header',
  tableCellSelected: 'rte-table-cell-selected',
  tableSelection: 'rte-table-selection',
  hr: 'rte-hr',
  indent: 'rte-indent',
};

export default defaultTheme;
