name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for creating an issue! We appreciate your feedback and will address it as soon as possible."
        pr-message: "Amazing! You've made it this far. We are truly grateful for your contribution."
